version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"   # AMQP port
            - "15672:15672" # RabbitMQ UI port
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
    
    datasimulator:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./DataSimulator"]
   
    iotcontroller:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./IoTController"]