services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"   # AMQP port
            - "15672:15672" # RabbitMQ UI port
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
            
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"   # MongoDB port
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    
    datasimulator:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./DataSimulator"]
   
    iotcontroller:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./IoTController"]
        
    ruleengine:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./RuleEngine"]
        
    prometheus:
        image: prom/prometheus:latest
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - "9090:9090" # Prometheus UI
        depends_on:
          - iotcontroller
          
    grafana:
        image: grafana/grafana:latest
        ports:
          - "3000:3000" # Grafana UI
        depends_on:
          - prometheus
        environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
        
networks:
    default:
        name: monitoring_network