services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"   # AMQP port
            - "15672:15672" # RabbitMQ UI port
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
            
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"   # MongoDB port
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    
    elasticsearch:
        image: elasticsearch:7.17.26
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            
    logstash:
        image: logstash:7.17.26
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        ports:
            - "5044:5044"  # For Logstash input
        depends_on:
            - elasticsearch
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
            interval: 30s       # Time between health check attempts
            timeout: 10s        # Time to wait for a response
            retries: 5          # Number of retries before marking as unhealthy
            start_period: 20s   # Grace period before starting health checks
    
    kibana:
        image: kibana:7.17.26
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
    
    datasimulator:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./DataSimulator"]
   
    iotcontroller:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
            logstash:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./IoTController"]
        
    ruleengine:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
            logstash:
                condition: service_healthy
        environment:
            - RABBITMQ_HOST=rabbitmq
        command: ["./RuleEngine"]
        
    prometheus:
        image: prom/prometheus:latest
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - "9090:9090" # Prometheus UI
        depends_on:
          - iotcontroller
          
    grafana:
        image: grafana/grafana:latest
        ports:
          - "3000:3000" # Grafana UI
        depends_on:
          - prometheus
        environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
        
networks:
    default:
        name: monitoring_network